nlp = [
    {'speaker': 'speaker_03', 'start': Decimal('0.0'), 'end': Decimal('0.96'), 'sentence': " that's what i was going for.", 'emotion': 'positive', 'dialogue': 'Statement-non-opinion'},
    {'speaker': 'speaker_03', 'start': Decimal('1.06'), 'end': Decimal('1.66'), 'sentence': ' you like that?', 'emotion': 'positive', 'dialogue': 'Yes-No-Question'},
    {'speaker': 'speaker_03', 'start': Decimal('1.84'), 'end': Decimal('2.0'), 'sentence': ' okay.', 'emotion': 'positive', 'dialogue': 'Conventional-closing'},
    {'speaker': 'speaker_04', 'start': Decimal('2.56'), 'end': Decimal('4.74'), 'sentence': " it's not obviously negative.", 'emotion': 'positive', 'dialogue': 'Statement-non-opinion'},
    {'speaker': 'speaker_04', 'start': Decimal('5.04'), 'end': Decimal('5.9'), 'sentence': " so we're saying,", 'emotion': 'positive', 'dialogue': 'Statement-opinion'},
    {'speaker': 'speaker_04', 'start': Decimal('5.98'), 'end': Decimal('7.44'), 'sentence': ' because it really does lend itself', 'emotion': 'positive', 'dialogue': 'Statement-opinion'},
    {'speaker': 'speaker_04', 'start': Decimal('7.44'), 'end': Decimal('9.26'), 'sentence': ' to being a comparison', 'emotion': 'positive', 'dialogue': 'Abandoned or Turn-Exit'},
    {'speaker': 'speaker_04', 'start': Decimal('9.26'), 'end': Decimal('10.62'), 'sentence': ' more than a competitive piece', 'emotion': 'positive', 'dialogue': 'Abandoned or Turn-Exit'},
    {'speaker': 'speaker_04', 'start': Decimal('10.62'), 'end': Decimal('11.22'), 'sentence': ' because of that,', 'emotion': 'positive', 'dialogue': 'Abandoned or Turn-Exit'},
    {'speaker': 'speaker_04', 'start': Decimal('11.28'), 'end': Decimal('12.02'), 'sentence': " because there's no,", 'emotion': 'positive', 'dialogue': 'Statement-opinion'},
    {'speaker': 'speaker_04', 'start': Decimal('12.42'), 'end': Decimal('13.94'), 'sentence': ' you know, these folks at 37%', 'emotion': 'positive', 'dialogue': 'Abandoned or Turn-Exit'},
    {'speaker': 'speaker_04', 'start': Decimal('13.94'), 'end': Decimal('15.28'), 'sentence': " are in the red and they're terrible.", 'emotion': 'positive', 'dialogue': 'Statement-non-opinion'},
    {'speaker': 'speaker_04', 'start': Decimal('15.42'), 'end': Decimal('16.56'), 'sentence': ' they just have less green', 'emotion': 'positive', 'dialogue': 'Statement-non-opinion'},
    {'speaker': 'speaker_04', 'start': Decimal('16.56'), 'end': Decimal('17.900000000000002'), 'sentence': ' or we would have less green.', 'emotion': 'positive', 'dialogue': 'Statement-non-opinion'},
    {'speaker': 'speaker_04', 'start': Decimal('18.48'), 'end': Decimal('20.48'), 'sentence': " so it's not being worse.", 'emotion': 'positive', 'dialogue': 'Statement-non-opinion'},
    {'speaker': 'speaker_04', 'start': Decimal('20.56'), 'end': Decimal('21.54'), 'sentence': " it's being less good.", 'emotion': 'positive', 'dialogue': 'Statement-opinion'},
    {'speaker': 'speaker_04', 'start': Decimal('21.54'), 'end': Decimal('25.24'), 'sentence': ' and i think that lends itself', 'emotion': 'positive', 'dialogue': 'Statement-opinion'},
    {'speaker': 'speaker_04', 'start': Decimal('25.24'), 'end': Decimal('27.92'), 'sentence': ' to working with,', 'emotion': 'positive', 'dialogue': 'Abandoned or Turn-Exit'},
    {'speaker': 'speaker_04', 'start': Decimal('27.98'), 'end': Decimal('29.66'), 'sentence': ' you know, all the coopetition', 'emotion': 'positive', 'dialogue': 'Statement-opinion'},
    {'speaker': 'speaker_04', 'start': Decimal('29.66'), 'end': Decimal('31.06'), 'sentence': ' situations we were talking about.', 'emotion': 'positive', 'dialogue': 'Statement-non-opinion'},
    {'speaker': 'speaker_02', 'start': Decimal('31.76'), 'end': Decimal('34.76'), 'sentence': " yeah, that's the goal is we want", 'emotion': 'positive', 'dialogue': 'Statement-non-opinion'},
    {'speaker': 'speaker_02', 'start': Decimal('34.76'), 'end': Decimal('36.68'), 'sentence': ' to generate a helpful asset', 'emotion': 'positive', 'dialogue': 'Abandoned or Turn-Exit'},
    {'speaker': 'speaker_02', 'start': Decimal('36.68'), 'end': Decimal('37.84'), 'sentence': ' for the industry.', 'emotion': 'positive', 'dialogue': 'Abandoned or Turn-Exit'},
    {'speaker': 'speaker_02', 'start': Decimal('38.5'), 'end': Decimal('40.26'), 'sentence': ' this is not just like marketing shill.', 'emotion': 'positive', 'dialogue': 'Statement-opinion'},
    {'speaker': 'speaker_02', 'start': Decimal('40.44'), 'end': Decimal('41.76'), 'sentence': ' this should be like a helpful page.', 'emotion': 'positive', 'dialogue': 'Statement-opinion'},
    {'speaker': 'speaker_02', 'start': Decimal('42.86'), 'end': Decimal('44.72'), 'sentence': ' so yeah, the goal is to have a comparison', 'emotion': 'positive', 'dialogue': 'Statement-non-opinion'},
    {'speaker': 'speaker_02', 'start': Decimal('44.72'), 'end': Decimal('46.52'), 'sentence': ' comparing devops tools,', 'emotion': 'positive', 'dialogue': 'Abandoned or Turn-Exit'},
    {'speaker': 'speaker_02', 'start': Decimal('46.84'), 'end': Decimal('48.02'), 'sentence': ' not a, you know,', 'emotion': 'positive', 'dialogue': 'Statement-non-opinion'},
    {'speaker': 'speaker_02', 'start': Decimal('48.1'), 'end': Decimal('49.14'), 'sentence': ' this is all of our competitors', 'emotion': 'positive', 'dialogue': 'Statement-non-opinion'},
    {'speaker': 'speaker_02', 'start': Decimal('49.14'), 'end': Decimal('49.88'), 'sentence': " and why we're better.", 'emotion': 'positive', 'dialogue': 'Statement-non-opinion'},
    {'speaker': 'speaker_02', 'start': Decimal('50.16'), 'end': Decimal('50.6'), 'sentence': ' yeah.', 'emotion': 'positive', 'dialogue': 'Uninterpretable'},
    {'speaker': 'speaker_00', 'start': Decimal('51.1'), 'end': Decimal('53.8'), 'sentence': ' i think from a competitive mindset', 'emotion': 'positive', 'dialogue': 'Statement-opinion'},
    {'speaker': 'speaker_00', 'start': Decimal('53.8'), 'end': Decimal('55.260000000000005'), 'sentence': " and for me, i'm like, let's go hard.", 'emotion': 'positive', 'dialogue': 'Statement-non-opinion'},
    {'speaker': 'speaker_00', 'start': Decimal('55.7'), 'end': Decimal('56.72'), 'sentence': " let's put some red on there.", 'emotion': 'positive', 'dialogue': 'Action-directive'},
    {'speaker': 'speaker_00', 'start': Decimal('57.84'), 'end': Decimal('59.48'), 'sentence': " that's just the way i think, right?", 'emotion': 'positive', 'dialogue': 'Yes-No-Question'},
    {'speaker': 'speaker_00', 'start': Decimal('59.48'), 'end': Decimal('60.78'), 'sentence': ' so, but i brought it up', 'emotion': 'positive', 'dialogue': 'Statement-non-opinion'},
    {'speaker': 'speaker_00', 'start': Decimal('60.78'), 'end': Decimal('62.36'), 'sentence': " and for now we're going to stick with the green.", 'emotion': 'positive', 'dialogue': 'Statement-non-opinion'},
    {'speaker': 'speaker_00', 'start': Decimal('62.48'), 'end': Decimal('63.18'), 'sentence': ' they recommend it.', 'emotion': 'positive', 'dialogue': 'Statement-non-opinion'},
    {'speaker': 'speaker_00', 'start': Decimal('63.26'), 'end': Decimal('64.2'), 'sentence': ' we stick with the green', 'emotion': 'positive', 'dialogue': 'Statement-non-opinion'},
    {'speaker': 'speaker_00', 'start': Decimal('64.2'), 'end': Decimal('65.5'), 'sentence': ' and see how it goes.', 'emotion': 'positive', 'dialogue': 'Statement-non-opinion'},
    {'speaker': 'speaker_00', 'start': Decimal('65.58'), 'end': Decimal('66.24'), 'sentence': " but i don't know.", 'emotion': 'positive', 'dialogue': 'Hedge'},
    {'speaker': 'speaker_00', 'start': Decimal('66.24'), 'end': Decimal('68.84'), 'sentence': ' i was feeling the red and yellow too.', 'emotion': 'positive', 'dialogue': 'Statement-non-opinion'},
    {'speaker': 'speaker_04', 'start': Decimal('69.66'), 'end': Decimal('71.22'), 'sentence': ' it is easy on the eyes.', 'emotion': 'positive', 'dialogue': 'Statement-non-opinion'},
    {'speaker': 'speaker_04', 'start': Decimal('71.86'), 'end': Decimal('73.32'), 'sentence': " there's something to be said for that.", 'emotion': 'positive', 'dialogue': 'Statement-opinion'},
    {'speaker': 'speaker_04', 'start': Decimal('73.58'), 'end': Decimal('74.8'), 'sentence': ' so yeah.', 'emotion': 'positive', 'dialogue': 'Uninterpretable'},
    {'speaker': 'speaker_02', 'start': Decimal('76.69999999999999'), 'end': Decimal('77.1'), 'sentence': ' cool.', 'emotion': 'positive', 'dialogue': 'Abandoned or Turn-Exit'},
    {'speaker': 'speaker_02', 'start': Decimal('77.3'), 'end': Decimal('79.44'), 'sentence': " well, we're almost up on time,", 'emotion': 'positive', 'dialogue': 'Statement-non-opinion'},
    {'speaker': 'speaker_02', 'start': Decimal('79.5'), 'end': Decimal('80.74'), 'sentence': ' but i did want to share one thing', 'emotion': 'positive', 'dialogue': 'Statement-non-opinion'},
    {'speaker': 'speaker_02', 'start': Decimal('80.74'), 'end': Decimal('81.94'), 'sentence': ' that kind of came in', 'emotion': 'positive', 'dialogue': 'Abandoned or Turn-Exit'},
    {'speaker': 'speaker_02', 'start': Decimal('81.94'), 'end': Decimal('84.62'), 'sentence': ' like basically friday.', 'emotion': 'positive', 'dialogue': 'Statement-non-opinion'},
    {'speaker': 'speaker_02', 'start': Decimal('85.1'), 'end': Decimal('86.9'), 'sentence': ' it was like late thursday for me.', 'emotion': 'positive', 'dialogue': 'Statement-non-opinion'},
    {'speaker': 'speaker_02', 'start': Decimal('87.58'), 'end': Decimal('88.42'), 'sentence': ' so this,', 'emotion': 'positive', 'dialogue': 'Uninterpretable'},
    {'speaker': 'speaker_02', 'start': Decimal('88.42'), 'end': Decimal('90.52'), 'sentence': ' this is another thing.', 'emotion': 'positive', 'dialogue': 'Statement-non-opinion'},
    {'speaker': 'speaker_02', 'start': Decimal('90.58'), 'end': Decimal('91.56'), 'sentence': ' a lot of these things', 'emotion': 'positive', 'dialogue': 'Abandoned or Turn-Exit'},
    {'speaker': 'speaker_02', 'start': Decimal('91.56'), 'end': Decimal('93.22'), 'sentence': " i don't have like a ton of context on.", 'emotion': 'positive', 'dialogue': 'Statement-non-opinion'},
    {'speaker': 'speaker_02', 'start': Decimal('94.16'), 'end': Decimal('95.2'), 'sentence': ' i just know like,', 'emotion': 'positive', 'dialogue': 'Statement-non-opinion'},
    {'speaker': 'speaker_02', 'start': Decimal('95.3'), 'end': Decimal('96.5'), 'sentence': " we're just trying to up our game.", 'emotion': 'positive', 'dialogue': 'Statement-non-opinion'},
    {'speaker': 'speaker_02', 'start': Decimal('96.56'), 'end': Decimal('97.66'), 'sentence': " so like, hey, let's move fast", 'emotion': 'positive', 'dialogue': 'Statement-non-opinion'},
    {'speaker': 'speaker_02', 'start': Decimal('97.66'), 'end': Decimal('98.66'), 'sentence': ' and do the best we can do.', 'emotion': 'positive', 'dialogue': 'Abandoned or Turn-Exit'},
    {'speaker': 'speaker_02', 'start': Decimal('100.52'), 'end': Decimal('101.56'), 'sentence': ' so this is a little bit', 'emotion': 'positive', 'dialogue': 'Statement-opinion'},
    {'speaker': 'speaker_02', 'start': Decimal('101.56'), 'end': Decimal('103.62'), 'sentence': ' of a messaging framework.', 'emotion': 'positive', 'dialogue': 'Abandoned or Turn-Exit'},
    {'speaker': 'speaker_02', 'start': Decimal('103.88'), 'end': Decimal('105.06'), 'sentence': ' and then the assignment', 'emotion': 'positive', 'dialogue': 'Statement-non-opinion'},
    {'speaker': 'speaker_02', 'start': Decimal('105.06'), 'end': Decimal('106.36'), 'sentence': ' that was given to me', 'emotion': 'positive', 'dialogue': 'Abandoned or Turn-Exit'},
    {'speaker': 'speaker_02', 'start': Decimal('106.36'), 'end': Decimal('108.98'), 'sentence': ' was to fill in these boxes here.', 'emotion': 'positive', 'dialogue': 'Statement-non-opinion'},
    {'speaker': 'speaker_02', 'start': Decimal('110.24'), 'end': Decimal('113.34'), 'sentence': ' so, and then this was the fodder', 'emotion': 'positive', 'dialogue': 'Statement-non-opinion'},
    {'speaker': 'speaker_02', 'start': Decimal('113.34'), 'end': Decimal('115.1'), 'sentence': ' that i got.', 'emotion': 'positive', 'dialogue': 'Abandoned or Turn-Exit'},
    {'speaker': 'speaker_02', 'start': Decimal('116.16'), 'end': Decimal('118.22'), 'sentence': ' so there was these ones that said like,', 'emotion': 'positive', 'dialogue': 'Statement-non-opinion'},
    {'speaker': 'speaker_02', 'start': Decimal('118.42'), 'end': Decimal('120.3'), 'sentence': ' from roadmap to company vision,', 'emotion': 'positive', 'dialogue': 'Abandoned or Turn-Exit'},
    {'speaker': 'speaker_02', 'start': Decimal('120.42'), 'end': Decimal('121.24'), 'sentence': ' we are transparent', 'emotion': 'positive', 'dialogue': 'Statement-opinion'},
    {'speaker': 'speaker_02', 'start': Decimal('121.24'), 'end': Decimal('123.44'), 'sentence': ' and a single source of truth,', 'emotion': 'positive', 'dialogue': 'Abandoned or Turn-Exit'},
    {'speaker': 'speaker_02', 'start': Decimal('123.72'), 'end': Decimal('124.72'), 'sentence': ' countless possibilities.', 'emotion': 'positive', 'dialogue': 'Abandoned or Turn-Exit'},
    {'speaker': 'speaker_02', 'start': Decimal('125.36'), 'end': Decimal('126.56'), 'sentence': " honestly, i think this one's really like", 'emotion': 'positive', 'dialogue': 'Statement-opinion'},
    {'speaker': 'speaker_02', 'start': Decimal('126.56'), 'end': Decimal('127.6'), 'sentence': ' really pithy and catchy.', 'emotion': 'positive', 'dialogue': 'Abandoned or Turn-Exit'},
    {'speaker': 'speaker_02', 'start': Decimal('128.22'), 'end': Decimal('129.4'), 'sentence': ' i really like it.', 'emotion': 'positive', 'dialogue': 'Statement-non-opinion'},
    {'speaker': 'speaker_02', 'start': Decimal('130.4'), 'end': Decimal('131.5'), 'sentence': ' i really liked,', 'emotion': 'positive', 'dialogue': 'Statement-non-opinion'},
    {'speaker': 'speaker_02', 'start': Decimal('131.7'), 'end': Decimal('133.0'), 'sentence': " what's the other one that i like", 'emotion': 'positive', 'dialogue': 'Statement-non-opinion'},
    {'speaker': 'speaker_02', 'start': Decimal('133.0'), 'end': Decimal('133.96'), 'sentence': ' that not everyone does?', 'emotion': 'positive', 'dialogue': 'Yes-No-Question'},
    {'speaker': 'speaker_02', 'start': Decimal('136.44'), 'end': Decimal('137.86'), 'sentence': ' all in one for everyone.', 'emotion': 'positive', 'dialogue': 'Abandoned or Turn-Exit'},
    {'speaker': 'speaker_02', 'start': Decimal('138.64'), 'end': Decimal('140.2'), 'sentence': " so i just, i don't know.", 'emotion': 'positive', 'dialogue': 'Hedge'},
    {'speaker': 'speaker_02', 'start': Decimal('140.28'), 'end': Decimal('141.06'), 'sentence': ' i like, i just think', 'emotion': 'positive', 'dialogue': 'Statement-opinion'},
    {'speaker': 'speaker_02', 'start': Decimal('141.06'), 'end': Decimal('142.32'), 'sentence': " so there's something catchy about that.", 'emotion': 'positive', 'dialogue': 'Statement-opinion'},
    {'speaker': 'speaker_02', 'start': Decimal('143.480
]
